### ISSUE TITLE
关于使用问题

### ISSUE THREAD

**Issue by jwh5566** [Mrxiaoxie/ConfigModifyTool#1]
你好  我看properties.json 中CommonInfo里面有pg和redis的配置 ，需要这些吗？？？
`"aPaaS":{
        "account-rest":{ #  这个是什么意思啊？  是目录吗？？
            "props":{
                "server.port":"9021",     # 这里是要修改的配置项吗？
                "messageserv.url":"http://172.16.0.161:8092/message",
                "web.url":"http://172.16.0.163:7000"
            },
            "yamls":{

            }
        }`

**Comment by Mrxiaoxie** [comment]
嗯嗯 正如你说的那样
